# Generated by Django 3.2.9 on 2022-01-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistepformmodel',
            name='box_1',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='box_2',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='box_3',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='box_4',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='box_5',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='box_6',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='box_7',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='box_8',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='box_9',
            field=models.TextField(max_length=300),
        ),
    ]
